# ===============================
# APPLICATION CONFIG
# ===============================
spring.application.name=jilamart
server.port=${PORT:8080}

# ===============================
# DATABASE CONFIG (Render / Env ??????)
# ===============================
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

# ??? PostgreSQL use ?? ??? ?? (Render DB)
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONNECTION POOL
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=FhczvbGF459akBdjgIhvPlD1QPUxUjlFj0z9qcx5UDQ=
jwt.expiration=86400000

# ===============================
# RAZORPAY CONFIG
# ===============================
razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}

spring.mail.host=smtp.hostinger.com
spring.mail.port=465
spring.mail.username=bihargoldbrand@biharigraphic.com
spring.mail.password=G!64s*Jl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true