package com.biharigraphic.jilamart.exception.enums;

public enum ErrorCode {
    USERNAME_NOT_FOUND,
    PHONE_REGISTERED,
    INVALID_PASSWORD,
    ROLE_NOT_FOUND,
    WRONG_PASSWORD_ENTERED,
    USER_ROLE_NOT_MATCHED,
    INVALID_OR_EXPIRED_TOKEN,
    USER_NOT_FOUND_FOR_USERNAME,
    INVALID_GOOGLE_ID_TOKEN,
    PHONE_NUMBER_NOT_FOUND,
    INCORRECT_OTP,
    EXPIRED_OTP,
    USED_OTP,
    EMAIL_ALREADY_REGISTERED,
    EMAIL_NOT_REGISTERED,
    PHONE_EMAIL_NOT_OF_USER,
    USER_NOT_FOUND,
    INVALID_USER
}